export type UNFPAFormType = {
  program_id: 6;
  unique_case_id: string;
  registration_date: Date | null;
  case_type: string;
  safe_house_shelter_name: string;
  district: string;
  municipality: string;
  full_name: string;
  contact_number: string;
  permanent_province_address: string;
  permanent_district_address: string;
  municipality_or_ward: string;
  temporary_address: string;
  citizenship_or_id_type: string;
  citizenship_id_no: string;
  dependent_children: string;
  date_of_incident: Date | null;
  location_of_incident: string;
  type_of_violence: string;
  subtype: string;
  perpetrator_relationship: string;
  perpetrator_gender: string;
  perpetrator_age: string;
  perpetrator_address: string;
  police_case_filed: string;
  case_registration_number: string;
  legal_protection_order: string;
  previous_incidents_or_repeated_violence: string;
  specify_details: string;
  additional_information_or_notes: string;
};
