#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [ "$CI" = "true" ] || [ "$BRANCH" = "main" ]; then
  echo "Skipping pre-push checks on $BRANCH or CI"
  exit 0
fi

echo "🔍 Running ESLint and TypeScript checks before push..."
npm run lint && npm run type-check
